#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'You must specify a directory for your project to exist in.'
    exit 1
fi

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

dir="$(pwd)/$1"
mkdir $dir

cp -r "$SCRIPTPATH/project/" $dir