#!/bin/bash 

#lldb -S util/lldb/breakpoints

SRCDIR="src/"
SRCEXT="cpp"
SOURCES=$(find $SRCDIR -type f -name *.$SRCEXT)
LLDBSCRIPT="$(pwd)/.tmp/breakpoints"

rm $LLDBSCRIPT
touch $LLDBSCRIPT

#echo "file bin/lexer" >> $LLDBSCRIPT

re='^[0-9]+$'

for source in $SOURCES
do
  filename=$(realpath $source)
  echo $filename
  lineno=$(grep -n '\/\/-BREAKPOINT-' $source | cut -d: -f 1)
  if [[ $lineno =~ $re ]] ; then
    echo -e "\t Breakpoint found at: $filename :: $lineno"
    echo "breakpoint set -f $filename -l $lineno" >> $LLDBSCRIPT
  fi
done